// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotArm.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BotArm_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BotArm_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BotArm_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BotArm_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BotArm_2eproto;
namespace cas {
namespace proto {
class BotArm;
struct BotArmDefaultTypeInternal;
extern BotArmDefaultTypeInternal _BotArm_default_instance_;
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> ::cas::proto::BotArm* Arena::CreateMaybeMessage<::cas::proto::BotArm>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cas {
namespace proto {

// ===================================================================

class BotArm final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cas.proto.BotArm) */ {
 public:
  inline BotArm() : BotArm(nullptr) {}
  ~BotArm() override;
  explicit PROTOBUF_CONSTEXPR BotArm(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BotArm(const BotArm& from);
  BotArm(BotArm&& from) noexcept
    : BotArm() {
    *this = ::std::move(from);
  }

  inline BotArm& operator=(const BotArm& from) {
    CopyFrom(from);
    return *this;
  }
  inline BotArm& operator=(BotArm&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BotArm& default_instance() {
    return *internal_default_instance();
  }
  static inline const BotArm* internal_default_instance() {
    return reinterpret_cast<const BotArm*>(
               &_BotArm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BotArm& a, BotArm& b) {
    a.Swap(&b);
  }
  inline void Swap(BotArm* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BotArm* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BotArm* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BotArm>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BotArm& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BotArm& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BotArm* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cas.proto.BotArm";
  }
  protected:
  explicit BotArm(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataBufferFieldNumber = 1,
  };
  // bytes data_buffer = 1;
  void clear_data_buffer();
  const std::string& data_buffer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data_buffer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data_buffer();
  PROTOBUF_NODISCARD std::string* release_data_buffer();
  void set_allocated_data_buffer(std::string* data_buffer);
  private:
  const std::string& _internal_data_buffer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data_buffer(const std::string& value);
  std::string* _internal_mutable_data_buffer();
  public:

  // @@protoc_insertion_point(class_scope:cas.proto.BotArm)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_buffer_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BotArm_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BotArm

// bytes data_buffer = 1;
inline void BotArm::clear_data_buffer() {
  data_buffer_.ClearToEmpty();
}
inline const std::string& BotArm::data_buffer() const {
  // @@protoc_insertion_point(field_get:cas.proto.BotArm.data_buffer)
  return _internal_data_buffer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BotArm::set_data_buffer(ArgT0&& arg0, ArgT... args) {
 
 data_buffer_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cas.proto.BotArm.data_buffer)
}
inline std::string* BotArm::mutable_data_buffer() {
  std::string* _s = _internal_mutable_data_buffer();
  // @@protoc_insertion_point(field_mutable:cas.proto.BotArm.data_buffer)
  return _s;
}
inline const std::string& BotArm::_internal_data_buffer() const {
  return data_buffer_.Get();
}
inline void BotArm::_internal_set_data_buffer(const std::string& value) {
  
  data_buffer_.Set(value, GetArenaForAllocation());
}
inline std::string* BotArm::_internal_mutable_data_buffer() {
  
  return data_buffer_.Mutable(GetArenaForAllocation());
}
inline std::string* BotArm::release_data_buffer() {
  // @@protoc_insertion_point(field_release:cas.proto.BotArm.data_buffer)
  return data_buffer_.Release();
}
inline void BotArm::set_allocated_data_buffer(std::string* data_buffer) {
  if (data_buffer != nullptr) {
    
  } else {
    
  }
  data_buffer_.SetAllocated(data_buffer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_buffer_.IsDefault()) {
    data_buffer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cas.proto.BotArm.data_buffer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BotArm_2eproto
