// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotArm.proto

#include "BotArm.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cas {
namespace proto {
PROTOBUF_CONSTEXPR BotArm::BotArm(
    ::_pbi::ConstantInitialized)
  : data_buffer_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct BotArmDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BotArmDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BotArmDefaultTypeInternal() {}
  union {
    BotArm _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BotArmDefaultTypeInternal _BotArm_default_instance_;
}  // namespace proto
}  // namespace cas
static ::_pb::Metadata file_level_metadata_BotArm_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_BotArm_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_BotArm_2eproto = nullptr;

const uint32_t TableStruct_BotArm_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotArm, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotArm, data_buffer_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cas::proto::BotArm)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cas::proto::_BotArm_default_instance_._instance,
};

const char descriptor_table_protodef_BotArm_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014BotArm.proto\022\tcas.proto\"\035\n\006BotArm\022\023\n\013d"
  "ata_buffer\030\001 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_BotArm_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_BotArm_2eproto = {
    false, false, 64, descriptor_table_protodef_BotArm_2eproto,
    "BotArm.proto",
    &descriptor_table_BotArm_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_BotArm_2eproto::offsets,
    file_level_metadata_BotArm_2eproto, file_level_enum_descriptors_BotArm_2eproto,
    file_level_service_descriptors_BotArm_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_BotArm_2eproto_getter() {
  return &descriptor_table_BotArm_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_BotArm_2eproto(&descriptor_table_BotArm_2eproto);
namespace cas {
namespace proto {

// ===================================================================

class BotArm::_Internal {
 public:
};

BotArm::BotArm(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:cas.proto.BotArm)
}
BotArm::BotArm(const BotArm& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  data_buffer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    data_buffer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data_buffer().empty()) {
    data_buffer_.Set(from._internal_data_buffer(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:cas.proto.BotArm)
}

inline void BotArm::SharedCtor() {
data_buffer_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  data_buffer_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BotArm::~BotArm() {
  // @@protoc_insertion_point(destructor:cas.proto.BotArm)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BotArm::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  data_buffer_.Destroy();
}

void BotArm::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BotArm::Clear() {
// @@protoc_insertion_point(message_clear_start:cas.proto.BotArm)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_buffer_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BotArm::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes data_buffer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_data_buffer();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BotArm::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cas.proto.BotArm)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data_buffer = 1;
  if (!this->_internal_data_buffer().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_data_buffer(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cas.proto.BotArm)
  return target;
}

size_t BotArm::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cas.proto.BotArm)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data_buffer = 1;
  if (!this->_internal_data_buffer().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data_buffer());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BotArm::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BotArm::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BotArm::GetClassData() const { return &_class_data_; }

void BotArm::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BotArm *>(to)->MergeFrom(
      static_cast<const BotArm &>(from));
}


void BotArm::MergeFrom(const BotArm& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cas.proto.BotArm)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data_buffer().empty()) {
    _internal_set_data_buffer(from._internal_data_buffer());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BotArm::CopyFrom(const BotArm& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cas.proto.BotArm)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BotArm::IsInitialized() const {
  return true;
}

void BotArm::InternalSwap(BotArm* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &data_buffer_, lhs_arena,
      &other->data_buffer_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BotArm::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BotArm_2eproto_getter, &descriptor_table_BotArm_2eproto_once,
      file_level_metadata_BotArm_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cas::proto::BotArm*
Arena::CreateMaybeMessage< ::cas::proto::BotArm >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cas::proto::BotArm >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
