// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotCar.proto

#include "BotCar.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cas {
namespace proto {
PROTOBUF_CONSTEXPR BotCar::BotCar(
    ::_pbi::ConstantInitialized)
  : move_sequence_(){}
struct BotCarDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BotCarDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BotCarDefaultTypeInternal() {}
  union {
    BotCar _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BotCarDefaultTypeInternal _BotCar_default_instance_;
}  // namespace proto
}  // namespace cas
static ::_pb::Metadata file_level_metadata_BotCar_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_BotCar_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_BotCar_2eproto = nullptr;

const uint32_t TableStruct_BotCar_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotCar, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotCar, move_sequence_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cas::proto::BotCar)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cas::proto::_BotCar_default_instance_._instance,
};

const char descriptor_table_protodef_BotCar_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014BotCar.proto\022\tcas.proto\"\037\n\006BotCar\022\025\n\rm"
  "ove_sequence\030\001 \003(\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_BotCar_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_BotCar_2eproto = {
    false, false, 66, descriptor_table_protodef_BotCar_2eproto,
    "BotCar.proto",
    &descriptor_table_BotCar_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_BotCar_2eproto::offsets,
    file_level_metadata_BotCar_2eproto, file_level_enum_descriptors_BotCar_2eproto,
    file_level_service_descriptors_BotCar_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_BotCar_2eproto_getter() {
  return &descriptor_table_BotCar_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_BotCar_2eproto(&descriptor_table_BotCar_2eproto);
namespace cas {
namespace proto {

// ===================================================================

class BotCar::_Internal {
 public:
};

BotCar::BotCar(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  move_sequence_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:cas.proto.BotCar)
}
BotCar::BotCar(const BotCar& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      move_sequence_(from.move_sequence_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cas.proto.BotCar)
}

inline void BotCar::SharedCtor() {
}

BotCar::~BotCar() {
  // @@protoc_insertion_point(destructor:cas.proto.BotCar)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BotCar::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BotCar::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BotCar::Clear() {
// @@protoc_insertion_point(message_clear_start:cas.proto.BotCar)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  move_sequence_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BotCar::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float move_sequence = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_move_sequence(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_move_sequence(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BotCar::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cas.proto.BotCar)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float move_sequence = 1;
  if (this->_internal_move_sequence_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_move_sequence(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cas.proto.BotCar)
  return target;
}

size_t BotCar::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cas.proto.BotCar)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float move_sequence = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_move_sequence_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BotCar::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BotCar::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BotCar::GetClassData() const { return &_class_data_; }

void BotCar::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BotCar *>(to)->MergeFrom(
      static_cast<const BotCar &>(from));
}


void BotCar::MergeFrom(const BotCar& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cas.proto.BotCar)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  move_sequence_.MergeFrom(from.move_sequence_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BotCar::CopyFrom(const BotCar& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cas.proto.BotCar)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BotCar::IsInitialized() const {
  return true;
}

void BotCar::InternalSwap(BotCar* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  move_sequence_.InternalSwap(&other->move_sequence_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BotCar::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BotCar_2eproto_getter, &descriptor_table_BotCar_2eproto_once,
      file_level_metadata_BotCar_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cas::proto::BotCar*
Arena::CreateMaybeMessage< ::cas::proto::BotCar >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cas::proto::BotCar >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
