// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotGripper.proto

#include "BotGripper.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cas {
namespace proto {
PROTOBUF_CONSTEXPR BotGripper::BotGripper(
    ::_pbi::ConstantInitialized)
  : status_(false){}
struct BotGripperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BotGripperDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BotGripperDefaultTypeInternal() {}
  union {
    BotGripper _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BotGripperDefaultTypeInternal _BotGripper_default_instance_;
}  // namespace proto
}  // namespace cas
static ::_pb::Metadata file_level_metadata_BotGripper_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_BotGripper_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_BotGripper_2eproto = nullptr;

const uint32_t TableStruct_BotGripper_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotGripper, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotGripper, status_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cas::proto::BotGripper)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cas::proto::_BotGripper_default_instance_._instance,
};

const char descriptor_table_protodef_BotGripper_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020BotGripper.proto\022\tcas.proto\"\034\n\nBotGrip"
  "per\022\016\n\006status\030\001 \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_BotGripper_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_BotGripper_2eproto = {
    false, false, 67, descriptor_table_protodef_BotGripper_2eproto,
    "BotGripper.proto",
    &descriptor_table_BotGripper_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_BotGripper_2eproto::offsets,
    file_level_metadata_BotGripper_2eproto, file_level_enum_descriptors_BotGripper_2eproto,
    file_level_service_descriptors_BotGripper_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_BotGripper_2eproto_getter() {
  return &descriptor_table_BotGripper_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_BotGripper_2eproto(&descriptor_table_BotGripper_2eproto);
namespace cas {
namespace proto {

// ===================================================================

class BotGripper::_Internal {
 public:
};

BotGripper::BotGripper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:cas.proto.BotGripper)
}
BotGripper::BotGripper(const BotGripper& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:cas.proto.BotGripper)
}

inline void BotGripper::SharedCtor() {
status_ = false;
}

BotGripper::~BotGripper() {
  // @@protoc_insertion_point(destructor:cas.proto.BotGripper)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BotGripper::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BotGripper::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BotGripper::Clear() {
// @@protoc_insertion_point(message_clear_start:cas.proto.BotGripper)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BotGripper::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BotGripper::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cas.proto.BotGripper)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cas.proto.BotGripper)
  return target;
}

size_t BotGripper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cas.proto.BotGripper)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BotGripper::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BotGripper::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BotGripper::GetClassData() const { return &_class_data_; }

void BotGripper::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BotGripper *>(to)->MergeFrom(
      static_cast<const BotGripper &>(from));
}


void BotGripper::MergeFrom(const BotGripper& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cas.proto.BotGripper)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _internal_set_status(from._internal_status());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BotGripper::CopyFrom(const BotGripper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cas.proto.BotGripper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BotGripper::IsInitialized() const {
  return true;
}

void BotGripper::InternalSwap(BotGripper* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(status_, other->status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BotGripper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BotGripper_2eproto_getter, &descriptor_table_BotGripper_2eproto_once,
      file_level_metadata_BotGripper_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cas::proto::BotGripper*
Arena::CreateMaybeMessage< ::cas::proto::BotGripper >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cas::proto::BotGripper >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
