// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotLed.proto

#include "BotLed.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cas {
namespace proto {
PROTOBUF_CONSTEXPR BotLed::BotLed(
    ::_pbi::ConstantInitialized)
  : mode_(0)
{}
struct BotLedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BotLedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BotLedDefaultTypeInternal() {}
  union {
    BotLed _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BotLedDefaultTypeInternal _BotLed_default_instance_;
}  // namespace proto
}  // namespace cas
static ::_pb::Metadata file_level_metadata_BotLed_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_BotLed_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_BotLed_2eproto = nullptr;

const uint32_t TableStruct_BotLed_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotLed, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotLed, mode_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cas::proto::BotLed)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cas::proto::_BotLed_default_instance_._instance,
};

const char descriptor_table_protodef_BotLed_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014BotLed.proto\022\tcas.proto\"U\n\006BotLed\022$\n\004m"
  "ode\030\001 \001(\0162\026.cas.proto.BotLed.Mode\"%\n\004Mod"
  "e\022\t\n\005CLOSE\020\000\022\t\n\005GREEN\020\001\022\007\n\003RED\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_BotLed_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_BotLed_2eproto = {
    false, false, 120, descriptor_table_protodef_BotLed_2eproto,
    "BotLed.proto",
    &descriptor_table_BotLed_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_BotLed_2eproto::offsets,
    file_level_metadata_BotLed_2eproto, file_level_enum_descriptors_BotLed_2eproto,
    file_level_service_descriptors_BotLed_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_BotLed_2eproto_getter() {
  return &descriptor_table_BotLed_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_BotLed_2eproto(&descriptor_table_BotLed_2eproto);
namespace cas {
namespace proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BotLed_Mode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_BotLed_2eproto);
  return file_level_enum_descriptors_BotLed_2eproto[0];
}
bool BotLed_Mode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr BotLed_Mode BotLed::CLOSE;
constexpr BotLed_Mode BotLed::GREEN;
constexpr BotLed_Mode BotLed::RED;
constexpr BotLed_Mode BotLed::Mode_MIN;
constexpr BotLed_Mode BotLed::Mode_MAX;
constexpr int BotLed::Mode_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class BotLed::_Internal {
 public:
};

BotLed::BotLed(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:cas.proto.BotLed)
}
BotLed::BotLed(const BotLed& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  mode_ = from.mode_;
  // @@protoc_insertion_point(copy_constructor:cas.proto.BotLed)
}

inline void BotLed::SharedCtor() {
mode_ = 0;
}

BotLed::~BotLed() {
  // @@protoc_insertion_point(destructor:cas.proto.BotLed)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BotLed::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BotLed::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BotLed::Clear() {
// @@protoc_insertion_point(message_clear_start:cas.proto.BotLed)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  mode_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BotLed::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .cas.proto.BotLed.Mode mode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_mode(static_cast<::cas::proto::BotLed_Mode>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BotLed::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cas.proto.BotLed)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .cas.proto.BotLed.Mode mode = 1;
  if (this->_internal_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cas.proto.BotLed)
  return target;
}

size_t BotLed::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cas.proto.BotLed)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .cas.proto.BotLed.Mode mode = 1;
  if (this->_internal_mode() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_mode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BotLed::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BotLed::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BotLed::GetClassData() const { return &_class_data_; }

void BotLed::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BotLed *>(to)->MergeFrom(
      static_cast<const BotLed &>(from));
}


void BotLed::MergeFrom(const BotLed& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cas.proto.BotLed)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_mode() != 0) {
    _internal_set_mode(from._internal_mode());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BotLed::CopyFrom(const BotLed& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cas.proto.BotLed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BotLed::IsInitialized() const {
  return true;
}

void BotLed::InternalSwap(BotLed* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(mode_, other->mode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BotLed::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BotLed_2eproto_getter, &descriptor_table_BotLed_2eproto_once,
      file_level_metadata_BotLed_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cas::proto::BotLed*
Arena::CreateMaybeMessage< ::cas::proto::BotLed >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cas::proto::BotLed >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
