// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cas.Proto {

  /// <summary>Holder for reflection information generated from DataMessage.proto</summary>
  public static partial class DataMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for DataMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFEYXRhTWVzc2FnZS5wcm90bxIJY2FzLnByb3RvGgpNZXNoLnByb3RvGhFT",
            "b3VuZFNvdXJjZS5wcm90bxoRVGVtcEFuZEh1bWkucHJvdG8aDEJvdENhci5w",
            "cm90bxoQQm90R3JpcHBlci5wcm90bxoOQm90TW90b3IucHJvdG8aDEJvdEFy",
            "bS5wcm90bxoMQm90TGVkLnByb3RvIq4ECgtEYXRhTWVzc2FnZRIpCgR0eXBl",
            "GAEgASgOMhsuY2FzLnByb3RvLkRhdGFNZXNzYWdlLlR5cGUSHwoEbWVzaBgC",
            "IAEoCzIPLmNhcy5wcm90by5NZXNoSAASLgoMc291bmRfc291cmNlGAMgASgL",
            "MhYuY2FzLnByb3RvLlNvdW5kU291cmNlSAASJAoHYm90X2NhchgEIAEoCzIR",
            "LmNhcy5wcm90by5Cb3RDYXJIABIsCgtib3RfZ3JpcHBlchgFIAEoCzIVLmNh",
            "cy5wcm90by5Cb3RHcmlwcGVySAASKAoJYm90X21vdG9yGAYgASgLMhMuY2Fz",
            "LnByb3RvLkJvdE1vdG9ySAASJAoHYm90X2FybRgHIAEoCzIRLmNhcy5wcm90",
            "by5Cb3RBcm1IABIkCgdib3RfbGVkGAggASgLMhEuY2FzLnByb3RvLkJvdExl",
            "ZEgAEi8KDXRlbXBfYW5kX2h1bWkYCSABKAsyFi5jYXMucHJvdG8uVGVtcEFu",
            "ZEh1bWlIACKfAQoEVHlwZRIJCgVPVEhFUhAAEggKBE1FU0gQARIWCglFWElU",
            "X01FU0gQ////////////ARIQCgxTT1VORF9TT1VSQ0UQAhILCgdCT1RfQ0FS",
            "EAMSDwoLQk9UX0dSSVBQRVIQBBINCglCT1RfTU9UT1IQBRILCgdCT1RfQVJN",
            "EAYSCwoHQk9UX0xFRBAHEhEKDVRFTVBfQU5EX0hVTUkQCEIGCgRkYXRhYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cas.Proto.MeshReflection.Descriptor, global::Cas.Proto.SoundSourceReflection.Descriptor, global::Cas.Proto.TempAndHumiReflection.Descriptor, global::Cas.Proto.BotCarReflection.Descriptor, global::Cas.Proto.BotGripperReflection.Descriptor, global::Cas.Proto.BotMotorReflection.Descriptor, global::Cas.Proto.BotArmReflection.Descriptor, global::Cas.Proto.BotLedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cas.Proto.DataMessage), global::Cas.Proto.DataMessage.Parser, new[]{ "Type", "Mesh", "SoundSource", "BotCar", "BotGripper", "BotMotor", "BotArm", "BotLed", "TempAndHumi" }, new[]{ "Data" }, new[]{ typeof(global::Cas.Proto.DataMessage.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataMessage : pb::IMessage<DataMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataMessage> _parser = new pb::MessageParser<DataMessage>(() => new DataMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DataMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cas.Proto.DataMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage(DataMessage other) : this() {
      type_ = other.type_;
      switch (other.DataCase) {
        case DataOneofCase.Mesh:
          Mesh = other.Mesh.Clone();
          break;
        case DataOneofCase.SoundSource:
          SoundSource = other.SoundSource.Clone();
          break;
        case DataOneofCase.BotCar:
          BotCar = other.BotCar.Clone();
          break;
        case DataOneofCase.BotGripper:
          BotGripper = other.BotGripper.Clone();
          break;
        case DataOneofCase.BotMotor:
          BotMotor = other.BotMotor.Clone();
          break;
        case DataOneofCase.BotArm:
          BotArm = other.BotArm.Clone();
          break;
        case DataOneofCase.BotLed:
          BotLed = other.BotLed.Clone();
          break;
        case DataOneofCase.TempAndHumi:
          TempAndHumi = other.TempAndHumi.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataMessage Clone() {
      return new DataMessage(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Cas.Proto.DataMessage.Types.Type type_ = global::Cas.Proto.DataMessage.Types.Type.Other;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.DataMessage.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "mesh" field.</summary>
    public const int MeshFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.Mesh Mesh {
      get { return dataCase_ == DataOneofCase.Mesh ? (global::Cas.Proto.Mesh) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Mesh;
      }
    }

    /// <summary>Field number for the "sound_source" field.</summary>
    public const int SoundSourceFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.SoundSource SoundSource {
      get { return dataCase_ == DataOneofCase.SoundSource ? (global::Cas.Proto.SoundSource) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.SoundSource;
      }
    }

    /// <summary>Field number for the "bot_car" field.</summary>
    public const int BotCarFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.BotCar BotCar {
      get { return dataCase_ == DataOneofCase.BotCar ? (global::Cas.Proto.BotCar) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.BotCar;
      }
    }

    /// <summary>Field number for the "bot_gripper" field.</summary>
    public const int BotGripperFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.BotGripper BotGripper {
      get { return dataCase_ == DataOneofCase.BotGripper ? (global::Cas.Proto.BotGripper) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.BotGripper;
      }
    }

    /// <summary>Field number for the "bot_motor" field.</summary>
    public const int BotMotorFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.BotMotor BotMotor {
      get { return dataCase_ == DataOneofCase.BotMotor ? (global::Cas.Proto.BotMotor) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.BotMotor;
      }
    }

    /// <summary>Field number for the "bot_arm" field.</summary>
    public const int BotArmFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.BotArm BotArm {
      get { return dataCase_ == DataOneofCase.BotArm ? (global::Cas.Proto.BotArm) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.BotArm;
      }
    }

    /// <summary>Field number for the "bot_led" field.</summary>
    public const int BotLedFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.BotLed BotLed {
      get { return dataCase_ == DataOneofCase.BotLed ? (global::Cas.Proto.BotLed) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.BotLed;
      }
    }

    /// <summary>Field number for the "temp_and_humi" field.</summary>
    public const int TempAndHumiFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cas.Proto.TempAndHumi TempAndHumi {
      get { return dataCase_ == DataOneofCase.TempAndHumi ? (global::Cas.Proto.TempAndHumi) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.TempAndHumi;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Mesh = 2,
      SoundSource = 3,
      BotCar = 4,
      BotGripper = 5,
      BotMotor = 6,
      BotArm = 7,
      BotLed = 8,
      TempAndHumi = 9,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DataMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DataMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Mesh, other.Mesh)) return false;
      if (!object.Equals(SoundSource, other.SoundSource)) return false;
      if (!object.Equals(BotCar, other.BotCar)) return false;
      if (!object.Equals(BotGripper, other.BotGripper)) return false;
      if (!object.Equals(BotMotor, other.BotMotor)) return false;
      if (!object.Equals(BotArm, other.BotArm)) return false;
      if (!object.Equals(BotLed, other.BotLed)) return false;
      if (!object.Equals(TempAndHumi, other.TempAndHumi)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Cas.Proto.DataMessage.Types.Type.Other) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Mesh) hash ^= Mesh.GetHashCode();
      if (dataCase_ == DataOneofCase.SoundSource) hash ^= SoundSource.GetHashCode();
      if (dataCase_ == DataOneofCase.BotCar) hash ^= BotCar.GetHashCode();
      if (dataCase_ == DataOneofCase.BotGripper) hash ^= BotGripper.GetHashCode();
      if (dataCase_ == DataOneofCase.BotMotor) hash ^= BotMotor.GetHashCode();
      if (dataCase_ == DataOneofCase.BotArm) hash ^= BotArm.GetHashCode();
      if (dataCase_ == DataOneofCase.BotLed) hash ^= BotLed.GetHashCode();
      if (dataCase_ == DataOneofCase.TempAndHumi) hash ^= TempAndHumi.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Cas.Proto.DataMessage.Types.Type.Other) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Mesh) {
        output.WriteRawTag(18);
        output.WriteMessage(Mesh);
      }
      if (dataCase_ == DataOneofCase.SoundSource) {
        output.WriteRawTag(26);
        output.WriteMessage(SoundSource);
      }
      if (dataCase_ == DataOneofCase.BotCar) {
        output.WriteRawTag(34);
        output.WriteMessage(BotCar);
      }
      if (dataCase_ == DataOneofCase.BotGripper) {
        output.WriteRawTag(42);
        output.WriteMessage(BotGripper);
      }
      if (dataCase_ == DataOneofCase.BotMotor) {
        output.WriteRawTag(50);
        output.WriteMessage(BotMotor);
      }
      if (dataCase_ == DataOneofCase.BotArm) {
        output.WriteRawTag(58);
        output.WriteMessage(BotArm);
      }
      if (dataCase_ == DataOneofCase.BotLed) {
        output.WriteRawTag(66);
        output.WriteMessage(BotLed);
      }
      if (dataCase_ == DataOneofCase.TempAndHumi) {
        output.WriteRawTag(74);
        output.WriteMessage(TempAndHumi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Cas.Proto.DataMessage.Types.Type.Other) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Mesh) {
        output.WriteRawTag(18);
        output.WriteMessage(Mesh);
      }
      if (dataCase_ == DataOneofCase.SoundSource) {
        output.WriteRawTag(26);
        output.WriteMessage(SoundSource);
      }
      if (dataCase_ == DataOneofCase.BotCar) {
        output.WriteRawTag(34);
        output.WriteMessage(BotCar);
      }
      if (dataCase_ == DataOneofCase.BotGripper) {
        output.WriteRawTag(42);
        output.WriteMessage(BotGripper);
      }
      if (dataCase_ == DataOneofCase.BotMotor) {
        output.WriteRawTag(50);
        output.WriteMessage(BotMotor);
      }
      if (dataCase_ == DataOneofCase.BotArm) {
        output.WriteRawTag(58);
        output.WriteMessage(BotArm);
      }
      if (dataCase_ == DataOneofCase.BotLed) {
        output.WriteRawTag(66);
        output.WriteMessage(BotLed);
      }
      if (dataCase_ == DataOneofCase.TempAndHumi) {
        output.WriteRawTag(74);
        output.WriteMessage(TempAndHumi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Cas.Proto.DataMessage.Types.Type.Other) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Mesh) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mesh);
      }
      if (dataCase_ == DataOneofCase.SoundSource) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SoundSource);
      }
      if (dataCase_ == DataOneofCase.BotCar) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotCar);
      }
      if (dataCase_ == DataOneofCase.BotGripper) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotGripper);
      }
      if (dataCase_ == DataOneofCase.BotMotor) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotMotor);
      }
      if (dataCase_ == DataOneofCase.BotArm) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotArm);
      }
      if (dataCase_ == DataOneofCase.BotLed) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotLed);
      }
      if (dataCase_ == DataOneofCase.TempAndHumi) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TempAndHumi);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DataMessage other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Cas.Proto.DataMessage.Types.Type.Other) {
        Type = other.Type;
      }
      switch (other.DataCase) {
        case DataOneofCase.Mesh:
          if (Mesh == null) {
            Mesh = new global::Cas.Proto.Mesh();
          }
          Mesh.MergeFrom(other.Mesh);
          break;
        case DataOneofCase.SoundSource:
          if (SoundSource == null) {
            SoundSource = new global::Cas.Proto.SoundSource();
          }
          SoundSource.MergeFrom(other.SoundSource);
          break;
        case DataOneofCase.BotCar:
          if (BotCar == null) {
            BotCar = new global::Cas.Proto.BotCar();
          }
          BotCar.MergeFrom(other.BotCar);
          break;
        case DataOneofCase.BotGripper:
          if (BotGripper == null) {
            BotGripper = new global::Cas.Proto.BotGripper();
          }
          BotGripper.MergeFrom(other.BotGripper);
          break;
        case DataOneofCase.BotMotor:
          if (BotMotor == null) {
            BotMotor = new global::Cas.Proto.BotMotor();
          }
          BotMotor.MergeFrom(other.BotMotor);
          break;
        case DataOneofCase.BotArm:
          if (BotArm == null) {
            BotArm = new global::Cas.Proto.BotArm();
          }
          BotArm.MergeFrom(other.BotArm);
          break;
        case DataOneofCase.BotLed:
          if (BotLed == null) {
            BotLed = new global::Cas.Proto.BotLed();
          }
          BotLed.MergeFrom(other.BotLed);
          break;
        case DataOneofCase.TempAndHumi:
          if (TempAndHumi == null) {
            TempAndHumi = new global::Cas.Proto.TempAndHumi();
          }
          TempAndHumi.MergeFrom(other.TempAndHumi);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Cas.Proto.DataMessage.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Cas.Proto.Mesh subBuilder = new global::Cas.Proto.Mesh();
            if (dataCase_ == DataOneofCase.Mesh) {
              subBuilder.MergeFrom(Mesh);
            }
            input.ReadMessage(subBuilder);
            Mesh = subBuilder;
            break;
          }
          case 26: {
            global::Cas.Proto.SoundSource subBuilder = new global::Cas.Proto.SoundSource();
            if (dataCase_ == DataOneofCase.SoundSource) {
              subBuilder.MergeFrom(SoundSource);
            }
            input.ReadMessage(subBuilder);
            SoundSource = subBuilder;
            break;
          }
          case 34: {
            global::Cas.Proto.BotCar subBuilder = new global::Cas.Proto.BotCar();
            if (dataCase_ == DataOneofCase.BotCar) {
              subBuilder.MergeFrom(BotCar);
            }
            input.ReadMessage(subBuilder);
            BotCar = subBuilder;
            break;
          }
          case 42: {
            global::Cas.Proto.BotGripper subBuilder = new global::Cas.Proto.BotGripper();
            if (dataCase_ == DataOneofCase.BotGripper) {
              subBuilder.MergeFrom(BotGripper);
            }
            input.ReadMessage(subBuilder);
            BotGripper = subBuilder;
            break;
          }
          case 50: {
            global::Cas.Proto.BotMotor subBuilder = new global::Cas.Proto.BotMotor();
            if (dataCase_ == DataOneofCase.BotMotor) {
              subBuilder.MergeFrom(BotMotor);
            }
            input.ReadMessage(subBuilder);
            BotMotor = subBuilder;
            break;
          }
          case 58: {
            global::Cas.Proto.BotArm subBuilder = new global::Cas.Proto.BotArm();
            if (dataCase_ == DataOneofCase.BotArm) {
              subBuilder.MergeFrom(BotArm);
            }
            input.ReadMessage(subBuilder);
            BotArm = subBuilder;
            break;
          }
          case 66: {
            global::Cas.Proto.BotLed subBuilder = new global::Cas.Proto.BotLed();
            if (dataCase_ == DataOneofCase.BotLed) {
              subBuilder.MergeFrom(BotLed);
            }
            input.ReadMessage(subBuilder);
            BotLed = subBuilder;
            break;
          }
          case 74: {
            global::Cas.Proto.TempAndHumi subBuilder = new global::Cas.Proto.TempAndHumi();
            if (dataCase_ == DataOneofCase.TempAndHumi) {
              subBuilder.MergeFrom(TempAndHumi);
            }
            input.ReadMessage(subBuilder);
            TempAndHumi = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Cas.Proto.DataMessage.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Cas.Proto.Mesh subBuilder = new global::Cas.Proto.Mesh();
            if (dataCase_ == DataOneofCase.Mesh) {
              subBuilder.MergeFrom(Mesh);
            }
            input.ReadMessage(subBuilder);
            Mesh = subBuilder;
            break;
          }
          case 26: {
            global::Cas.Proto.SoundSource subBuilder = new global::Cas.Proto.SoundSource();
            if (dataCase_ == DataOneofCase.SoundSource) {
              subBuilder.MergeFrom(SoundSource);
            }
            input.ReadMessage(subBuilder);
            SoundSource = subBuilder;
            break;
          }
          case 34: {
            global::Cas.Proto.BotCar subBuilder = new global::Cas.Proto.BotCar();
            if (dataCase_ == DataOneofCase.BotCar) {
              subBuilder.MergeFrom(BotCar);
            }
            input.ReadMessage(subBuilder);
            BotCar = subBuilder;
            break;
          }
          case 42: {
            global::Cas.Proto.BotGripper subBuilder = new global::Cas.Proto.BotGripper();
            if (dataCase_ == DataOneofCase.BotGripper) {
              subBuilder.MergeFrom(BotGripper);
            }
            input.ReadMessage(subBuilder);
            BotGripper = subBuilder;
            break;
          }
          case 50: {
            global::Cas.Proto.BotMotor subBuilder = new global::Cas.Proto.BotMotor();
            if (dataCase_ == DataOneofCase.BotMotor) {
              subBuilder.MergeFrom(BotMotor);
            }
            input.ReadMessage(subBuilder);
            BotMotor = subBuilder;
            break;
          }
          case 58: {
            global::Cas.Proto.BotArm subBuilder = new global::Cas.Proto.BotArm();
            if (dataCase_ == DataOneofCase.BotArm) {
              subBuilder.MergeFrom(BotArm);
            }
            input.ReadMessage(subBuilder);
            BotArm = subBuilder;
            break;
          }
          case 66: {
            global::Cas.Proto.BotLed subBuilder = new global::Cas.Proto.BotLed();
            if (dataCase_ == DataOneofCase.BotLed) {
              subBuilder.MergeFrom(BotLed);
            }
            input.ReadMessage(subBuilder);
            BotLed = subBuilder;
            break;
          }
          case 74: {
            global::Cas.Proto.TempAndHumi subBuilder = new global::Cas.Proto.TempAndHumi();
            if (dataCase_ == DataOneofCase.TempAndHumi) {
              subBuilder.MergeFrom(TempAndHumi);
            }
            input.ReadMessage(subBuilder);
            TempAndHumi = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the DataMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("OTHER")] Other = 0,
        [pbr::OriginalName("MESH")] Mesh = 1,
        [pbr::OriginalName("EXIT_MESH")] ExitMesh = -1,
        [pbr::OriginalName("SOUND_SOURCE")] SoundSource = 2,
        [pbr::OriginalName("BOT_CAR")] BotCar = 3,
        [pbr::OriginalName("BOT_GRIPPER")] BotGripper = 4,
        [pbr::OriginalName("BOT_MOTOR")] BotMotor = 5,
        [pbr::OriginalName("BOT_ARM")] BotArm = 6,
        [pbr::OriginalName("BOT_LED")] BotLed = 7,
        [pbr::OriginalName("TEMP_AND_HUMI")] TempAndHumi = 8,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
