// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempAndHumi.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TempAndHumi_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TempAndHumi_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TempAndHumi_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TempAndHumi_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TempAndHumi_2eproto;
namespace cas {
namespace proto {
class TempAndHumi;
struct TempAndHumiDefaultTypeInternal;
extern TempAndHumiDefaultTypeInternal _TempAndHumi_default_instance_;
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> ::cas::proto::TempAndHumi* Arena::CreateMaybeMessage<::cas::proto::TempAndHumi>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cas {
namespace proto {

// ===================================================================

class TempAndHumi final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cas.proto.TempAndHumi) */ {
 public:
  inline TempAndHumi() : TempAndHumi(nullptr) {}
  ~TempAndHumi() override;
  explicit PROTOBUF_CONSTEXPR TempAndHumi(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TempAndHumi(const TempAndHumi& from);
  TempAndHumi(TempAndHumi&& from) noexcept
    : TempAndHumi() {
    *this = ::std::move(from);
  }

  inline TempAndHumi& operator=(const TempAndHumi& from) {
    CopyFrom(from);
    return *this;
  }
  inline TempAndHumi& operator=(TempAndHumi&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TempAndHumi& default_instance() {
    return *internal_default_instance();
  }
  static inline const TempAndHumi* internal_default_instance() {
    return reinterpret_cast<const TempAndHumi*>(
               &_TempAndHumi_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TempAndHumi& a, TempAndHumi& b) {
    a.Swap(&b);
  }
  inline void Swap(TempAndHumi* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TempAndHumi* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TempAndHumi* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TempAndHumi>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TempAndHumi& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TempAndHumi& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TempAndHumi* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cas.proto.TempAndHumi";
  }
  protected:
  explicit TempAndHumi(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempFieldNumber = 1,
    kHumiFieldNumber = 2,
  };
  // float temp = 1;
  void clear_temp();
  float temp() const;
  void set_temp(float value);
  private:
  float _internal_temp() const;
  void _internal_set_temp(float value);
  public:

  // float humi = 2;
  void clear_humi();
  float humi() const;
  void set_humi(float value);
  private:
  float _internal_humi() const;
  void _internal_set_humi(float value);
  public:

  // @@protoc_insertion_point(class_scope:cas.proto.TempAndHumi)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float temp_;
  float humi_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TempAndHumi_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TempAndHumi

// float temp = 1;
inline void TempAndHumi::clear_temp() {
  temp_ = 0;
}
inline float TempAndHumi::_internal_temp() const {
  return temp_;
}
inline float TempAndHumi::temp() const {
  // @@protoc_insertion_point(field_get:cas.proto.TempAndHumi.temp)
  return _internal_temp();
}
inline void TempAndHumi::_internal_set_temp(float value) {
  
  temp_ = value;
}
inline void TempAndHumi::set_temp(float value) {
  _internal_set_temp(value);
  // @@protoc_insertion_point(field_set:cas.proto.TempAndHumi.temp)
}

// float humi = 2;
inline void TempAndHumi::clear_humi() {
  humi_ = 0;
}
inline float TempAndHumi::_internal_humi() const {
  return humi_;
}
inline float TempAndHumi::humi() const {
  // @@protoc_insertion_point(field_get:cas.proto.TempAndHumi.humi)
  return _internal_humi();
}
inline void TempAndHumi::_internal_set_humi(float value) {
  
  humi_ = value;
}
inline void TempAndHumi::set_humi(float value) {
  _internal_set_humi(value);
  // @@protoc_insertion_point(field_set:cas.proto.TempAndHumi.humi)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TempAndHumi_2eproto
