// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotCar.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BotCar_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BotCar_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BotCar_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BotCar_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BotCar_2eproto;
namespace cas {
namespace proto {
class BotCar;
struct BotCarDefaultTypeInternal;
extern BotCarDefaultTypeInternal _BotCar_default_instance_;
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> ::cas::proto::BotCar* Arena::CreateMaybeMessage<::cas::proto::BotCar>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cas {
namespace proto {

// ===================================================================

class BotCar final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cas.proto.BotCar) */ {
 public:
  inline BotCar() : BotCar(nullptr) {}
  ~BotCar() override;
  explicit constexpr BotCar(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BotCar(const BotCar& from);
  BotCar(BotCar&& from) noexcept
    : BotCar() {
    *this = ::std::move(from);
  }

  inline BotCar& operator=(const BotCar& from) {
    CopyFrom(from);
    return *this;
  }
  inline BotCar& operator=(BotCar&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BotCar& default_instance() {
    return *internal_default_instance();
  }
  static inline const BotCar* internal_default_instance() {
    return reinterpret_cast<const BotCar*>(
               &_BotCar_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BotCar& a, BotCar& b) {
    a.Swap(&b);
  }
  inline void Swap(BotCar* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BotCar* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BotCar* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BotCar>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BotCar& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BotCar& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BotCar* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cas.proto.BotCar";
  }
  protected:
  explicit BotCar(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMoveSequenceFieldNumber = 1,
  };
  // repeated int32 move_sequence = 1;
  int move_sequence_size() const;
  private:
  int _internal_move_sequence_size() const;
  public:
  void clear_move_sequence();
  private:
  int32_t _internal_move_sequence(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_move_sequence() const;
  void _internal_add_move_sequence(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_move_sequence();
  public:
  int32_t move_sequence(int index) const;
  void set_move_sequence(int index, int32_t value);
  void add_move_sequence(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      move_sequence() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_move_sequence();

  // @@protoc_insertion_point(class_scope:cas.proto.BotCar)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > move_sequence_;
  mutable std::atomic<int> _move_sequence_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BotCar_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BotCar

// repeated int32 move_sequence = 1;
inline int BotCar::_internal_move_sequence_size() const {
  return move_sequence_.size();
}
inline int BotCar::move_sequence_size() const {
  return _internal_move_sequence_size();
}
inline void BotCar::clear_move_sequence() {
  move_sequence_.Clear();
}
inline int32_t BotCar::_internal_move_sequence(int index) const {
  return move_sequence_.Get(index);
}
inline int32_t BotCar::move_sequence(int index) const {
  // @@protoc_insertion_point(field_get:cas.proto.BotCar.move_sequence)
  return _internal_move_sequence(index);
}
inline void BotCar::set_move_sequence(int index, int32_t value) {
  move_sequence_.Set(index, value);
  // @@protoc_insertion_point(field_set:cas.proto.BotCar.move_sequence)
}
inline void BotCar::_internal_add_move_sequence(int32_t value) {
  move_sequence_.Add(value);
}
inline void BotCar::add_move_sequence(int32_t value) {
  _internal_add_move_sequence(value);
  // @@protoc_insertion_point(field_add:cas.proto.BotCar.move_sequence)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
BotCar::_internal_move_sequence() const {
  return move_sequence_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
BotCar::move_sequence() const {
  // @@protoc_insertion_point(field_list:cas.proto.BotCar.move_sequence)
  return _internal_move_sequence();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
BotCar::_internal_mutable_move_sequence() {
  return &move_sequence_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
BotCar::mutable_move_sequence() {
  // @@protoc_insertion_point(field_mutable_list:cas.proto.BotCar.move_sequence)
  return _internal_mutable_move_sequence();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BotCar_2eproto
