// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BotMotor.proto

#include "BotMotor.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace cas {
namespace proto {
constexpr BotMotor::BotMotor(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : angle_(0){}
struct BotMotorDefaultTypeInternal {
  constexpr BotMotorDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~BotMotorDefaultTypeInternal() {}
  union {
    BotMotor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT BotMotorDefaultTypeInternal _BotMotor_default_instance_;
}  // namespace proto
}  // namespace cas
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_BotMotor_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_BotMotor_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_BotMotor_2eproto = nullptr;

const uint32_t TableStruct_BotMotor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotMotor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cas::proto::BotMotor, angle_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cas::proto::BotMotor)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cas::proto::_BotMotor_default_instance_),
};

const char descriptor_table_protodef_BotMotor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016BotMotor.proto\022\tcas.proto\"\031\n\010BotMotor\022"
  "\r\n\005angle\030\001 \001(\005b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_BotMotor_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BotMotor_2eproto = {
  false, false, 62, descriptor_table_protodef_BotMotor_2eproto, "BotMotor.proto", 
  &descriptor_table_BotMotor_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_BotMotor_2eproto::offsets,
  file_level_metadata_BotMotor_2eproto, file_level_enum_descriptors_BotMotor_2eproto, file_level_service_descriptors_BotMotor_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_BotMotor_2eproto_getter() {
  return &descriptor_table_BotMotor_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_BotMotor_2eproto(&descriptor_table_BotMotor_2eproto);
namespace cas {
namespace proto {

// ===================================================================

class BotMotor::_Internal {
 public:
};

BotMotor::BotMotor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cas.proto.BotMotor)
}
BotMotor::BotMotor(const BotMotor& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  angle_ = from.angle_;
  // @@protoc_insertion_point(copy_constructor:cas.proto.BotMotor)
}

inline void BotMotor::SharedCtor() {
angle_ = 0;
}

BotMotor::~BotMotor() {
  // @@protoc_insertion_point(destructor:cas.proto.BotMotor)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void BotMotor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BotMotor::ArenaDtor(void* object) {
  BotMotor* _this = reinterpret_cast< BotMotor* >(object);
  (void)_this;
}
void BotMotor::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void BotMotor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BotMotor::Clear() {
// @@protoc_insertion_point(message_clear_start:cas.proto.BotMotor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  angle_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BotMotor::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 angle = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          angle_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BotMotor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cas.proto.BotMotor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 angle = 1;
  if (this->_internal_angle() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_angle(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cas.proto.BotMotor)
  return target;
}

size_t BotMotor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cas.proto.BotMotor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 angle = 1;
  if (this->_internal_angle() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_angle());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BotMotor::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BotMotor::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BotMotor::GetClassData() const { return &_class_data_; }

void BotMotor::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BotMotor *>(to)->MergeFrom(
      static_cast<const BotMotor &>(from));
}


void BotMotor::MergeFrom(const BotMotor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cas.proto.BotMotor)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_angle() != 0) {
    _internal_set_angle(from._internal_angle());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BotMotor::CopyFrom(const BotMotor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cas.proto.BotMotor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BotMotor::IsInitialized() const {
  return true;
}

void BotMotor::InternalSwap(BotMotor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(angle_, other->angle_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BotMotor::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_BotMotor_2eproto_getter, &descriptor_table_BotMotor_2eproto_once,
      file_level_metadata_BotMotor_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cas::proto::BotMotor* Arena::CreateMaybeMessage< ::cas::proto::BotMotor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cas::proto::BotMotor >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
