// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Temperature.proto

#include "Temperature.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace cas {
namespace proto {
constexpr Temperature::Temperature(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : t_(0){}
struct TemperatureDefaultTypeInternal {
  constexpr TemperatureDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TemperatureDefaultTypeInternal() {}
  union {
    Temperature _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TemperatureDefaultTypeInternal _Temperature_default_instance_;
}  // namespace proto
}  // namespace cas
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Temperature_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Temperature_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Temperature_2eproto = nullptr;

const uint32_t TableStruct_Temperature_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cas::proto::Temperature, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cas::proto::Temperature, t_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cas::proto::Temperature)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cas::proto::_Temperature_default_instance_),
};

const char descriptor_table_protodef_Temperature_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021Temperature.proto\022\tcas.proto\"\030\n\013Temper"
  "ature\022\t\n\001t\030\001 \001(\002b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Temperature_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Temperature_2eproto = {
  false, false, 64, descriptor_table_protodef_Temperature_2eproto, "Temperature.proto", 
  &descriptor_table_Temperature_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_Temperature_2eproto::offsets,
  file_level_metadata_Temperature_2eproto, file_level_enum_descriptors_Temperature_2eproto, file_level_service_descriptors_Temperature_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Temperature_2eproto_getter() {
  return &descriptor_table_Temperature_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Temperature_2eproto(&descriptor_table_Temperature_2eproto);
namespace cas {
namespace proto {

// ===================================================================

class Temperature::_Internal {
 public:
};

Temperature::Temperature(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:cas.proto.Temperature)
}
Temperature::Temperature(const Temperature& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  t_ = from.t_;
  // @@protoc_insertion_point(copy_constructor:cas.proto.Temperature)
}

inline void Temperature::SharedCtor() {
t_ = 0;
}

Temperature::~Temperature() {
  // @@protoc_insertion_point(destructor:cas.proto.Temperature)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Temperature::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Temperature::ArenaDtor(void* object) {
  Temperature* _this = reinterpret_cast< Temperature* >(object);
  (void)_this;
}
void Temperature::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Temperature::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Temperature::Clear() {
// @@protoc_insertion_point(message_clear_start:cas.proto.Temperature)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  t_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Temperature::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float t = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          t_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Temperature::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cas.proto.Temperature)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float t = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_t = this->_internal_t();
  uint32_t raw_t;
  memcpy(&raw_t, &tmp_t, sizeof(tmp_t));
  if (raw_t != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_t(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cas.proto.Temperature)
  return target;
}

size_t Temperature::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cas.proto.Temperature)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float t = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_t = this->_internal_t();
  uint32_t raw_t;
  memcpy(&raw_t, &tmp_t, sizeof(tmp_t));
  if (raw_t != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Temperature::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Temperature::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Temperature::GetClassData() const { return &_class_data_; }

void Temperature::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Temperature *>(to)->MergeFrom(
      static_cast<const Temperature &>(from));
}


void Temperature::MergeFrom(const Temperature& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cas.proto.Temperature)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_t = from._internal_t();
  uint32_t raw_t;
  memcpy(&raw_t, &tmp_t, sizeof(tmp_t));
  if (raw_t != 0) {
    _internal_set_t(from._internal_t());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Temperature::CopyFrom(const Temperature& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cas.proto.Temperature)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Temperature::IsInitialized() const {
  return true;
}

void Temperature::InternalSwap(Temperature* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(t_, other->t_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Temperature::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Temperature_2eproto_getter, &descriptor_table_Temperature_2eproto_once,
      file_level_metadata_Temperature_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace cas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cas::proto::Temperature* Arena::CreateMaybeMessage< ::cas::proto::Temperature >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cas::proto::Temperature >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
